planner_server:
  ros__parameters:
    expected_planner_frequency: 5.0
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner::NavfnPlanner"
      tolerance: 0.5
      use_astar: true
      allow_unknown: false

global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 5.0
      publish_frequency: 2.0
      global_frame: map
      robot_base_frame: base_link
      width: 20
      height: 20
      resolution: 0.2
      origin_x: -10.0
      origin_y: -10.0
      track_unknown_space: false
      rolling_window: false
      always_send_full_costmap: true
      plugins: ["static_layer", "inflation_layer"]
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_topic: /costmap/occupancy_grid
        map_subscribe_transient_local: false
        subscribe_to_updates: false
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 1.0
        cost_scaling_factor: 5.0

lifecycle_manager:
  ros__parameters:
    autostart: true
    node_names: ["planner_server"]
    bond_timeout: 10.0
