planner_server:
  ros__parameters:
    expected_planner_frequency: 5.0
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner::NavfnPlanner"
      tolerance: 0.5
      use_astar: true
      allow_unknown: true

global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 5.0
      publish_frequency: 2.0
      global_frame: map
      robot_base_frame: base_link
      width: 40
      height: 40
      resolution: 0.3
      origin_x: -20.0
      origin_y: -20.0
      track_unknown_space: true
      rolling_window: false
      always_send_full_costmap: true
      plugins: ["static_layer"]
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_topic: /costmap/occupancy_grid
        map_subscribe_transient_local: false
        subscribe_to_updates: false

lifecycle_manager:
  ros__parameters:
    autostart: true
    node_names: ["planner_server"]
    bond_timeout: 10.0
